# Generated by Django 5.2.1 on 2025-05-29 16:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='نام استان')),
                ('slug', models.CharField(max_length=60, verbose_name='اسلاگ')),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='عرض جغرافیایی')),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='طول جغرافیایی')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='شناسه یکتا')),
            ],
            options={
                'verbose_name': 'استان',
                'verbose_name_plural': 'استان\u200cها',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='نام شهر')),
                ('slug', models.CharField(max_length=60, verbose_name='اسلاگ')),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='عرض جغرافیایی')),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='طول جغرافیایی')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='شناسه یکتا')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='address.province', verbose_name='استان')),
            ],
            options={
                'verbose_name': 'شهر',
                'verbose_name_plural': 'شهرها',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100, verbose_name='آدرس کامل')),
                ('phone', models.CharField(max_length=11, verbose_name='شماره تلفن')),
                ('zipcode', models.CharField(blank=True, max_length=12, null=True, verbose_name='کد پستی')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='address.city', verbose_name='شهر')),
                ('province', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='address.province', verbose_name='استان')),
            ],
            options={
                'verbose_name': 'آدرس',
                'verbose_name_plural': 'آدرس\u200cها',
            },
        ),
    ]
