# Generated by Django 5.2.1 on 2025-05-29 16:03

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام دسته\u200cبندی')),
                ('slug', models.SlugField(allow_unicode=True, help_text='برای استفاده در URLها، معمولا نسخه لاتین و خط\u200cفاصله\u200cدار نام است.', max_length=110, unique=True, verbose_name='اسلاگ (نامک)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FacilityFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام ویژگی')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات ویژگی')),
                ('icon_class', models.CharField(blank=True, help_text="مانند 'fa-wifi' برای Font Awesome", max_length=50, verbose_name='کلاس آیکون (اختیاری)')),
                ('feature_type', models.CharField(choices=[('positive', 'مثبت'), ('negative', 'منفی'), ('neutral', 'خنثی')], default='positive', max_length=10, verbose_name='نوع ویژگی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ویژگی سالن',
                'verbose_name_plural': 'ویژگی\u200cهای سالن',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, help_text='تاریخ میلادی را برای تعطیلی\u200cهای یکبار مصرف وارد کنید.', null=True, unique=True, verbose_name='تاریخ تعطیلی (میلادی)')),
                ('description', models.CharField(max_length=200, verbose_name='توضیحات')),
                ('is_recurring', models.BooleanField(default=False, help_text='اگر این تعطیلی هر سال تکرار می\u200cشود (بر اساس ماه و روز شمسی).', verbose_name='تعطیلی سالانه')),
                ('jalali_month', models.IntegerField(blank=True, help_text='برای تعطیلی\u200cهای تکرارشونده (1 تا 12).', null=True, verbose_name='ماه شمسی')),
                ('jalali_day', models.IntegerField(blank=True, help_text='برای تعطیلی\u200cهای تکرارشونده (1 تا 31).', null=True, verbose_name='روز شمسی')),
            ],
            options={
                'verbose_name': 'تعطیلی',
                'verbose_name_plural': 'تعطیلات',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='ReservationPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام پکیج')),
                ('duration_months', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='مدت پکیج (ماه)')),
                ('discount_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='درصد تخفیف پکیج')),
                ('min_sessions_per_month', models.IntegerField(default=4, help_text='برای اعمال تخفیف پکیج، حداقل تعداد رزرو ماهانه.', verbose_name='حداقل تعداد سانس در ماه')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'پکیج رزرو',
                'verbose_name_plural': 'پکیج\u200cهای رزرو',
                'ordering': ['duration_months'],
            },
        ),
        migrations.CreateModel(
            name='SessionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام آپشن')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات آپشن')),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='قیمت آپشن')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'آپشن سانس',
                'verbose_name_plural': 'آپشن\u200cهای سانس',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام تگ')),
                ('slug', models.SlugField(allow_unicode=True, max_length=110, unique=True, verbose_name='اسلاگ (نامک)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'تگ',
                'verbose_name_plural': 'تگ\u200cها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام تخفیف')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('discount_type', models.CharField(choices=[('percentage', 'درصدی'), ('fixed', 'مبلغ ثابت')], max_length=20, verbose_name='نوع تخفیف')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مقدار تخفیف (درصد یا مبلغ)')),
                ('target_type', models.CharField(choices=[('facility', 'سالن ورزشی'), ('session', 'سانس'), ('user', 'کاربر'), ('code', 'کد تخفیف'), ('all', 'همه موارد (تخفیف عمومی)')], max_length=20, verbose_name='هدف تخفیف')),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name="کد تخفیف (برای نوع 'کد تخفیف')")),
                ('start_date', models.DateField(verbose_name='تاریخ شروع')),
                ('end_date', models.DateField(verbose_name='تاریخ پایان')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('min_price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='حداقل مبلغ خرید برای اعمال تخفیف')),
                ('max_discount', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='حداکثر مبلغ قابل تخفیف (برای تخفیف درصدی)')),
                ('usage_limit', models.IntegerField(blank=True, help_text='تعداد دفعاتی که این تخفیف می\u200cتواند استفاده شود (null به معنای نامحدود).', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='محدودیت تعداد استفاده کلی')),
                ('used_count', models.IntegerField(default=0, editable=False, verbose_name='تعداد دفعات استفاده شده')),
                ('user_usage_limit', models.IntegerField(blank=True, help_text='تعداد دفعاتی که هر کاربر می\u200cتواند از این تخفیف استفاده کند (null به معنای نامحدود).', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='محدودیت استفاده برای هر کاربر')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to=settings.AUTH_USER_MODEL, verbose_name='کاربر مرتبط')),
            ],
            options={
                'verbose_name': 'تخفیف',
                'verbose_name_plural': 'تخفیف\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecurringReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='تاریخ شروع دوره')),
                ('end_date', models.DateField(verbose_name='تاریخ پایان دوره')),
                ('payment_frequency', models.CharField(choices=[('weekly', 'هفتگی'), ('monthly', 'ماهانه'), ('quarterly', 'سه ماهه'), ('yearly', 'سالانه')], default='monthly', max_length=20, verbose_name='دوره پرداخت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_reservations', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gym.reservationpackage', verbose_name='پکیج مرتبط (اختیاری)')),
            ],
            options={
                'verbose_name': 'رزرو دوره\u200cای',
                'verbose_name_plural': 'رزروهای دوره\u200cای',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاریخ رزرو')),
                ('status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('confirmed', 'تایید شده'), ('cancelled', 'لغو شده'), ('completed', 'انجام شده'), ('expired', 'منقضی شده (پرداخت نشده)')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('original_price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='قیمت اصلی سانس')),
                ('discount_amount', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='مبلغ تخفیف اعمال شده')),
                ('final_price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='قیمت نهایی پرداختنی')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت')),
                ('cancellation_reason', models.TextField(blank=True, verbose_name='دلیل لغو')),
                ('cancellation_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ لغو')),
                ('discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='gym.discount', verbose_name='تخفیف اعمال شده')),
                ('recurring_reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='individual_reservations', to='gym.recurringreservation', verbose_name='رزرو دوره\u200cای مرتبط')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'رزرو',
                'verbose_name_plural': 'رزروها',
                'ordering': ['-date', 'session_time__start_time'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '۱ ستاره ⭐'), (2, '۲ ستاره ⭐⭐'), (3, '۳ ستاره ⭐⭐⭐'), (4, '۴ ستاره ⭐⭐⭐⭐'), (5, '۵ ستاره ⭐⭐⭐⭐⭐')], verbose_name='امتیاز')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='نظر کاربر')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_approved', models.BooleanField(default=False, help_text='آیا این نظر در سایت نمایش داده شود؟', verbose_name='تایید شده توسط مدیر')),
                ('reservation', models.OneToOneField(help_text='هر رزرو فقط می\u200cتواند یک نظر داشته باشد.', on_delete=django.db.models.deletion.CASCADE, related_name='review', to='gym.reservation', verbose_name='رزرو مرتبط')),
            ],
            options={
                'verbose_name': 'نظر',
                'verbose_name_plural': 'نظرات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_name', models.CharField(max_length=100, verbose_name='نام سانس')),
                ('day_of_week', models.IntegerField(choices=[(0, 'شنبه'), (1, 'یکشنبه'), (2, 'دوشنبه'), (3, 'سه\u200cشنبه'), (4, 'چهارشنبه'), (5, 'پنج\u200cشنبه'), (6, 'جمعه')], verbose_name='روز هفته')),
                ('start_time', models.TimeField(verbose_name='زمان شروع')),
                ('end_time', models.TimeField(verbose_name='زمان پایان')),
                ('capacity', models.IntegerField(help_text='تعداد نفرات قابل رزرو در هر سانس', verbose_name='ظرفیت سانس')),
                ('price_type', models.CharField(choices=[('fixed', 'قیمت ثابت'), ('hourly', 'قیمت ساعتی'), ('dynamic', 'قیمت پویا (بر اساس قوانین قیمت\u200cگذاری)')], default='fixed', max_length=10, verbose_name='نوع قیمت\u200cگذاری')),
                ('fixed_price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='قیمت ثابت سانس')),
                ('hourly_price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='قیمت ساعتی سانس')),
                ('base_weekday_price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='قیمت پایه روزهای عادی (برای قیمت پویا)')),
                ('base_weekend_price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='قیمت پایه آخر هفته (برای قیمت پویا)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('options', models.ManyToManyField(blank=True, related_name='sessions', to='gym.sessionoption', verbose_name='آپشن\u200cهای قابل انتخاب')),
            ],
            options={
                'verbose_name': 'زمان سانس',
                'verbose_name_plural': 'زمان\u200cهای سانس',
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
        migrations.AddField(
            model_name='reservation',
            name='session_time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='gym.sessiontime', verbose_name='سانس'),
        ),
        migrations.AddField(
            model_name='recurringreservation',
            name='session_time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.sessiontime', verbose_name='سانس مورد نظر'),
        ),
        migrations.AddField(
            model_name='discount',
            name='session_time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='gym.sessiontime', verbose_name='سانس مرتبط'),
        ),
        migrations.CreateModel(
            name='SportFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام سالن')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('capacity', models.IntegerField(verbose_name='ظرفیت کلی سالن')),
                ('hourly_price', models.DecimalField(decimal_places=0, help_text='در صورتی که سانس قیمت ساعتی نداشته باشد، از این استفاده می\u200cشود.', max_digits=10, verbose_name='قیمت ساعتی پیش\u200cفرض سالن')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='تلفن')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='facilities', to='gym.category', verbose_name='دسته\u200cبندی\u200cها')),
                ('features', models.ManyToManyField(blank=True, related_name='facilities', to='gym.facilityfeature', verbose_name='ویژگی\u200cها')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_facilities', to=settings.AUTH_USER_MODEL, verbose_name='مدیر سالن')),
                ('tags', models.ManyToManyField(blank=True, related_name='facilities', to='gym.tag', verbose_name='تگ\u200cها')),
            ],
            options={
                'verbose_name': 'سالن ورزشی',
                'verbose_name_plural': 'سالن\u200cهای ورزشی',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='sessiontime',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_times', to='gym.sportfacility', verbose_name='سالن'),
        ),
        migrations.AddField(
            model_name='reservationpackage',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='gym.sportfacility', verbose_name='سالن'),
        ),
        migrations.CreateModel(
            name='PricingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام قانون')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('rule_type', models.CharField(choices=[('time_of_day', 'ساعت روز'), ('day_of_week', 'روز هفته'), ('date_range', 'بازه تاریخی'), ('special_day', 'روزهای خاص (مانند تعطیلات)'), ('peak_hours', 'ساعات اوج مصرف')], max_length=20, verbose_name='نوع قانون')),
                ('start_time_rule', models.TimeField(blank=True, null=True, verbose_name='ساعت شروع اعمال قانون')),
                ('end_time_rule', models.TimeField(blank=True, null=True, verbose_name='ساعت پایان اعمال قانون')),
                ('days_of_week', models.CharField(blank=True, help_text='شماره روزها با کاما جدا شود (0=شنبه, 1=یکشنبه, ..., 6=جمعه). مثال: 5,6 برای پنجشنبه و جمعه.', max_length=20, verbose_name='روزهای هفته شمسی')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='تاریخ شروع اعمال قانون')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پایان اعمال قانون')),
                ('price_adjustment_type', models.CharField(choices=[('percentage_increase', 'افزایش درصدی'), ('percentage_decrease', 'کاهش درصدی'), ('fixed_price', 'قیمت ثابت'), ('fixed_increase', 'افزایش ثابت'), ('fixed_decrease', 'کاهش ثابت')], max_length=20, verbose_name='نوع تنظیم قیمت')),
                ('adjustment_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مقدار تنظیم قیمت')),
                ('priority', models.IntegerField(default=0, help_text="قوانین با اولویت بالاتر (عدد بزرگتر) زودتر اعمال می\u200cشوند. قوانین 'fixed_price' باید بالاترین اولویت را داشته باشند.", verbose_name='اولویت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_rules', to='gym.sportfacility', verbose_name='سالن')),
            ],
            options={
                'verbose_name': 'قانون قیمت\u200cگذاری',
                'verbose_name_plural': 'قوانین قیمت\u200cگذاری',
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.AddField(
            model_name='discount',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='gym.sportfacility', verbose_name='سالن ورزشی مرتبط'),
        ),
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('user', 'session_time', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='sessiontime',
            unique_together={('facility', 'day_of_week', 'start_time', 'end_time')},
        ),
        migrations.CreateModel(
            name='FacilityGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='facility_gallery/', verbose_name='تصویر')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='توضیحات تصویر')),
                ('order', models.IntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_cover', models.BooleanField(default=False, help_text='آیا این تصویر اصلی سالن است؟', verbose_name='تصویر کاور')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='gym.sportfacility', verbose_name='سالن ورزشی')),
            ],
            options={
                'verbose_name': 'تصویر گالری سالن',
                'verbose_name_plural': 'گالری سالن\u200cها',
                'ordering': ['-is_cover', 'order', '-uploaded_at'],
                'unique_together': {('facility', 'image')},
            },
        ),
    ]
