# Generated by Django 5.2.1 on 2025-05-28 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='تاریخ تعطیلی')),
                ('description', models.CharField(max_length=200, verbose_name='توضیحات')),
                ('is_recurring', models.BooleanField(default=False, verbose_name='تعطیلی سالانه')),
                ('jalali_month', models.IntegerField(blank=True, null=True, verbose_name='ماه شمسی')),
                ('jalali_day', models.IntegerField(blank=True, null=True, verbose_name='روز شمسی')),
            ],
            options={
                'verbose_name': 'تعطیلی',
                'verbose_name_plural': 'تعطیلات',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='SportFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام سالن')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('capacity', models.IntegerField(verbose_name='ظرفیت')),
                ('hourly_price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='قیمت ساعتی')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='تلفن')),
                ('facilities', models.TextField(blank=True, verbose_name='امکانات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='مدیر سالن')),
            ],
            options={
                'verbose_name': 'سالن ورزشی',
                'verbose_name_plural': 'سالن های ورزشی',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SessionTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_name', models.CharField(max_length=100, verbose_name='نام سانس')),
                ('day_of_week', models.IntegerField(choices=[(0, 'شنبه'), (1, 'یکشنبه'), (2, 'دوشنبه'), (3, 'سه\u200cشنبه'), (4, 'چهارشنبه'), (5, 'پنج\u200cشنبه'), (6, 'جمعه')], verbose_name='روز هفته')),
                ('start_time', models.TimeField(verbose_name='زمان شروع')),
                ('end_time', models.TimeField(verbose_name='زمان پایان')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='قیمت')),
                ('price_override', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='قیمت ویژه')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_times', to='gym.sportfacility', verbose_name='سالن')),
            ],
            options={
                'verbose_name': 'زمان سانس',
                'verbose_name_plural': 'زمان\u200cهای سانس',
                'ordering': ['day_of_week', 'start_time'],
                'unique_together': {('facility', 'day_of_week', 'start_time', 'end_time')},
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('confirmed', 'تایید شده'), ('cancelled', 'لغو شده'), ('completed', 'انجام شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='قیمت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('session_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='gym.sessiontime', verbose_name='سانس')),
            ],
            options={
                'verbose_name': 'رزرو',
                'verbose_name_plural': 'رزروها',
                'ordering': ['-date', 'session_time__start_time'],
                'unique_together': {('session_time', 'date')},
            },
        ),
    ]
