# Generated by Django 5.2.1 on 2025-05-28 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessiontime',
            name='price',
        ),
        migrations.RemoveField(
            model_name='sessiontime',
            name='price_override',
        ),
        migrations.AddField(
            model_name='sessiontime',
            name='fixed_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='قیمت ثابت سانس'),
        ),
        migrations.AddField(
            model_name='sessiontime',
            name='hourly_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='قیمت ساعتی سانس'),
        ),
        migrations.AddField(
            model_name='sessiontime',
            name='price_type',
            field=models.CharField(choices=[('fixed', 'قیمت ثابت'), ('hourly', 'قیمت ساعتی')], default='fixed', max_length=10, verbose_name='نوع قیمت\u200cگذاری'),
        ),
    ]
