# Generated by Django 5.2.1 on 2025-05-28 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='تاریخ تعطیلی')),
                ('description', models.CharField(max_length=200, verbose_name='توضیحات')),
                ('is_recurring', models.BooleanField(default=False, verbose_name='تعطیلی سالانه')),
                ('jalali_month', models.IntegerField(blank=True, null=True, verbose_name='ماه شمسی')),
                ('jalali_day', models.IntegerField(blank=True, null=True, verbose_name='روز شمسی')),
            ],
            options={
                'verbose_name': 'تعطیلی',
                'verbose_name_plural': 'تعطیلات',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='ReservationPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام پکیج')),
                ('duration_months', models.IntegerField(verbose_name='مدت (ماه)')),
                ('discount_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='درصد تخفیف')),
                ('min_sessions_per_month', models.IntegerField(default=4, verbose_name='حداقل سانس در ماه')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'پکیج رزرو',
                'verbose_name_plural': 'پکیج\u200cهای رزرو',
                'ordering': ['duration_months'],
            },
        ),
        migrations.CreateModel(
            name='SessionTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_name', models.CharField(max_length=100, verbose_name='نام سانس')),
                ('day_of_week', models.IntegerField(choices=[(0, 'شنبه'), (1, 'یکشنبه'), (2, 'دوشنبه'), (3, 'سه\u200cشنبه'), (4, 'چهارشنبه'), (5, 'پنج\u200cشنبه'), (6, 'جمعه')], verbose_name='روز هفته')),
                ('start_time', models.TimeField(verbose_name='زمان شروع')),
                ('end_time', models.TimeField(verbose_name='زمان پایان')),
                ('capacity', models.IntegerField(help_text='تعداد نفرات قابل رزرو در هر سانس', verbose_name='ظرفیت سانس')),
                ('price_type', models.CharField(choices=[('fixed', 'قیمت ثابت'), ('hourly', 'قیمت ساعتی'), ('dynamic', 'قیمت پویا')], default='fixed', max_length=10, verbose_name='نوع قیمت\u200cگذاری')),
                ('fixed_price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='قیمت ثابت سانس')),
                ('hourly_price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='قیمت ساعتی سانس')),
                ('base_weekday_price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='قیمت پایه روزهای عادی')),
                ('base_weekend_price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='قیمت پایه آخر هفته')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'زمان سانس',
                'verbose_name_plural': 'زمان\u200cهای سانس',
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام تخفیف')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('discount_type', models.CharField(choices=[('percentage', 'درصدی'), ('fixed', 'مبلغ ثابت')], max_length=20, verbose_name='نوع تخفیف')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مقدار تخفیف')),
                ('target_type', models.CharField(choices=[('facility', 'سالن ورزشی'), ('session', 'سانس'), ('user', 'کاربر'), ('code', 'کد تخفیف')], max_length=20, verbose_name='نوع هدف')),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='کد تخفیف')),
                ('start_date', models.DateField(verbose_name='تاریخ شروع')),
                ('end_date', models.DateField(verbose_name='تاریخ پایان')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('min_price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='حداقل مبلغ')),
                ('max_discount', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='حداکثر مبلغ تخفیف')),
                ('usage_limit', models.IntegerField(blank=True, null=True, verbose_name='محدودیت استفاده')),
                ('used_count', models.IntegerField(default=0, verbose_name='تعداد استفاده')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('session_time', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='ai.sessiontime', verbose_name='سانس')),
            ],
            options={
                'verbose_name': 'تخفیف',
                'verbose_name_plural': 'تخفیف\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecurringReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='تاریخ شروع')),
                ('end_date', models.DateField(verbose_name='تاریخ پایان')),
                ('payment_frequency', models.CharField(choices=[('weekly', 'هفتگی'), ('monthly', 'ماهانه'), ('quarterly', 'سه ماهه'), ('yearly', 'سالانه')], default='monthly', max_length=20, verbose_name='دوره پرداخت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_reservations', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai.reservationpackage', verbose_name='پکیج')),
                ('session_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai.sessiontime', verbose_name='سانس')),
            ],
            options={
                'verbose_name': 'رزرو دوره\u200cای',
                'verbose_name_plural': 'رزروهای دوره\u200cای',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('confirmed', 'تایید شده'), ('cancelled', 'لغو شده'), ('completed', 'انجام شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('original_price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='قیمت اصلی')),
                ('calculated_price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='قیمت محاسبه شده')),
                ('discount_amount', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='مبلغ تخفیف')),
                ('final_price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='قیمت نهایی')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت')),
                ('cancellation_reason', models.TextField(blank=True, verbose_name='دلیل لغو')),
                ('cancellation_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ لغو')),
                ('discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='ai.discount', verbose_name='تخفیف')),
                ('recurring_reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='individual_reservations', to='ai.recurringreservation', verbose_name='رزرو دوره\u200cای')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('session_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='ai.sessiontime', verbose_name='سانس')),
            ],
            options={
                'verbose_name': 'رزرو',
                'verbose_name_plural': 'رزروها',
                'ordering': ['-date', 'session_time__start_time'],
                'unique_together': {('user', 'session_time', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '⭐'), (2, '⭐⭐'), (3, '⭐⭐⭐'), (4, '⭐⭐⭐⭐'), (5, '⭐⭐⭐⭐⭐')], verbose_name='امتیاز')),
                ('comment', models.TextField(blank=True, verbose_name='نظر')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_approved', models.BooleanField(default=False, verbose_name='تایید شده')),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='ai.reservation', verbose_name='رزرو')),
            ],
            options={
                'verbose_name': 'نظر',
                'verbose_name_plural': 'نظرات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SportFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام سالن')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('capacity', models.IntegerField(verbose_name='ظرفیت')),
                ('hourly_price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='قیمت ساعتی')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='تلفن')),
                ('facilities', models.TextField(blank=True, verbose_name='امکانات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='مدیر سالن')),
            ],
            options={
                'verbose_name': 'سالن ورزشی',
                'verbose_name_plural': 'سالن های ورزشی',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='sessiontime',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_times', to='ai.sportfacility', verbose_name='سالن'),
        ),
        migrations.AddField(
            model_name='reservationpackage',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='ai.sportfacility', verbose_name='سالن'),
        ),
        migrations.CreateModel(
            name='PricingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام قانون')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('rule_type', models.CharField(choices=[('time_of_day', 'ساعت روز'), ('day_of_week', 'روز هفته'), ('date_range', 'بازه تاریخی'), ('special_day', 'روزهای خاص'), ('peak_hours', 'ساعات شلوغ')], max_length=20, verbose_name='نوع قانون')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='ساعت شروع')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='ساعت پایان')),
                ('days_of_week', models.CharField(blank=True, help_text='شماره روزها با کاما جدا شود. مثال: 0,1,2 برای شنبه،یکشنبه،دوشنبه', max_length=20, verbose_name='روزهای هفته')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='تاریخ شروع')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پایان')),
                ('price_adjustment_type', models.CharField(choices=[('percentage_increase', 'افزایش درصدی'), ('percentage_decrease', 'کاهش درصدی'), ('fixed_price', 'قیمت ثابت'), ('fixed_increase', 'افزایش ثابت'), ('fixed_decrease', 'کاهش ثابت')], max_length=20, verbose_name='نوع تنظیم قیمت')),
                ('adjustment_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مقدار تنظیم')),
                ('priority', models.IntegerField(default=0, help_text='قوانین با اولویت بالاتر زودتر اعمال می\u200cشوند', verbose_name='اولویت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_rules', to='ai.sportfacility', verbose_name='سالن')),
            ],
            options={
                'verbose_name': 'قانون قیمت\u200cگذاری',
                'verbose_name_plural': 'قوانین قیمت\u200cگذاری',
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.AddField(
            model_name='discount',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='ai.sportfacility', verbose_name='سالن ورزشی'),
        ),
        migrations.AlterUniqueTogether(
            name='sessiontime',
            unique_together={('facility', 'day_of_week', 'start_time', 'end_time')},
        ),
    ]
